// Sample project data for seeding the Projects table

export const projects = [
  {
    userId: "user1",
    projectId: "proj1",
    name: "Factory Project in Co. Carlow",
    description: "The establishment of an Irish Whiskey Distillery & associated visitor facilities at Holloden Hse Demesne, Clorusk Lr, Royal Oak, Bagenalstown. Including distillery building, warehouses, visitor center, and infrastructure improvements.",
    category: "Industrial",
    startDate: "2014-12-09",
    endDate: "2015-10-27",
    budget: 11100000,
    completed: true,
    priority: 4,
    tags: ["distillery", "visitor-center", "warehouse", "industrial"],
    createdAt: "2014-02-17",
    updatedAt: "2014-12-09"
  },
  {
    userId: "user1",
    projectId: "proj2",
    name: "Light Industrial Unit in Co. Carlow",
    description: "Development for a single steel framed light industrial unit, associated car parking, site vehicular entrance, perimeter fencing, sign to front facade, connection to existing services and all ancillary site works.",
    category: "Industrial",
    startDate: "2015-03-23",
    endDate: "2016-01-21",
    budget: 438000,
    completed: true,
    priority: 2,
    tags: ["light-industrial", "steel", "car-parking", "fencing"],
    createdAt: "2014-10-28",
    updatedAt: "2015-03-23"
  },
  {
    userId: "user1",
    projectId: "proj3",
    name: "Applegreen Service Areas Development",
    description: "Development at a site of c. 4.74 ha at Junction 6 on the M9 Motorway located at Clocristic, Milford, Co. Carlow. The development will consist of an off-line motorway service area with amenities building, forecourt areas, and parking facilities.",
    category: "Commercial & Retail",
    startDate: "2017-04-23",
    endDate: "2018-02-01",
    budget: 2500000,
    completed: false,
    priority: 5,
    tags: ["service-station", "motorway", "retail", "forecourt"],
    createdAt: "2014-12-08",
    updatedAt: "2015-04-07"
  },
  {
    userId: "user2",
    projectId: "proj1",
    name: "Office Extension at Teagasc Research Centre",
    description: "The change of use of existing Coach House (a Protected Structure) to office use, re-planning and redevelopment internally, changes to roof structure, doors and windows and extension to the rear consisting of tiered lecture theatre and new car park areas.",
    category: "Commercial & Retail",
    startDate: "2016-11-26",
    endDate: "2017-08-22",
    budget: 480000,
    completed: true,
    priority: 3,
    tags: ["office", "extension", "lecture-theatre", "protected-structure"],
    createdAt: "2014-12-19",
    updatedAt: "2015-11-18"
  },
  {
    userId: "user2",
    projectId: "proj2",
    name: "Holistic Centre Conversion",
    description: "Change of use of existing warehouse and offices to a holistic teaching and treatment centre inclusive of single bed apartment for associated short term accommodation, for construction of a single storey extension to the existing office area, and for construction of a glasshouse in the adjoining garden area.",
    category: "Commercial & Retail",
    startDate: "2015-12-17",
    endDate: "2016-06-10",
    budget: 580000,
    completed: true,
    priority: 2,
    tags: ["conversion", "teaching", "treatment-center", "glasshouse", "extension"],
    createdAt: "2014-08-06",
    updatedAt: "2015-02-11"
  },
  {
    userId: "user3",
    projectId: "proj1",
    name: "3-Storey Office Block Development",
    description: "A new 3 storey office block with single storey link joining to 3 storey office block previously granted under Reg. Ref. 08/6049 together with all associated site and landscaping works.",
    category: "Commercial & Retail",
    startDate: "2015-10-17",
    endDate: "2016-07-24",
    budget: 1600000,
    completed: false,
    priority: 4,
    tags: ["office", "multi-storey", "commercial", "landscaping"],
    createdAt: "2014-04-30",
    updatedAt: "2014-08-15"
  }
];
